name: Generate clients

on:
  push:
    branches:
      - main
    paths:
      - 'api.yml'
  workflow_dispatch:

jobs:
  generate-clients:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Check version
      run: bin/check_version_bump.sh

    - name: Export API version as env variable
      run: echo "API_VERSION=$(sh ./bin/api_version.sh)" >> "$GITHUB_ENV"

    - name: Generate Go client
      uses: kpurdon/openapi-generator-action@v0.0.3
      with:
        args: "generate -i ./api.yml -g go -o ./gen/go/yf -c ./config-go.yml --additional-properties=packageVersion=${{ env.API_VERSION }} --git-repo-id ${{ github.event.repository.name }}/gen/go --git-user-id ${{ github.repository_owner }}"

    - name: Push changes and tag the latest version
      uses: EndBug/add-and-commit@v7.2.1
      with:
        add: './gen/'
        message: "Generate clients for version ${{ env.API_VERSION }}"
        tag: v${{ env.API_VERSION }}
